name: RLOM Univ CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  call-workflow-using-branch:
          uses: 3zbyjd/deployment_action/.github/workflows/action.yml@main 
  Build_Project:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

    #   - name: Install Dependencies
    #     run: npm install

    #   - name: npm run build
    #     run: npm run build

    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: rlomuniv
    #       path: dist/

    #   - name: Conneect to remote
    #     run: |
    #       Host demond
    #         HostName $SSH_HOST
    #         User $SSH_USER
    #         Ident
    #     env:
    #       SSH_USER: ${{ secrets.USERNAME }}
    #       SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #       SSH_HOST: ${{ secrets.HOST }}

      # - name: Copy artifact to remote        
        # uses: appleboy/scp-action@v0.1.4
        # with:
        #   host: ${{ secrets.HOST }}
        #   username: ${{ secrets.USERNAME }}
        #   port: ${{ secrets.PORT }}
        #   password: ${{ secrets.PASSPHRASE }}
        #   source: dist/
        #   overwrite: true
        #   target: ${{ secrets.TARGET }}
        #   tar_tmp_path: ${{ secrets.TMP_PATH }}
        #   tar_exec: ${{ secrets.TAR_PATH }}
